cbail:
  - "*"
lukebaker:
  - "*"
msalganik:
  - "*"
matnel:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
joshua-a-becker:
  - "_data/2018/northwestern/"
  - "2018/northwestern/"
allisonmorgan:
  - "_data/2018/boulder/"
  - "2018/boulder/"
