cbail:
  - "*"
lukebaker:
  - "*"
msalganik:
  - "*"
matnel:
  - "_data/2019/helsinki/"
  - "2019/helsinki/"
  - "2019/live-stream.md"
  - "_data/2019/istanbul/"
  - "2019/istanbul/"
juhopaak:
  - "_data/2019/helsinki/"
  - "2019/helsinki/"
  - "2019/live-stream.md"
UMTti:
  - "_data/2019/helsinki/"
  - "2019/helsinki/"
  - "2019/live-stream.md"
joshua-a-becker:
  - "_data/2019/chicago/"
  - "2019/chicago/"
  - "2019/live-stream.md"
dgzara:
  - "_data/2019/chicago/"
  - "2019/chicago/"
  - "2019/live-stream.md"
allisonmorgan:
  - "_data/2019/boulder/"
  - "2019/boulder/"
  - "2019/live-stream.md"
  - "2019/materials"
  - "2019/teaching-learning-materials.md"
visseho:
  - "_data/2019/capetown/"
  - "2019/capetown/"
  - "2019/live-stream.md"
  - "_data/2019/capetown/"
  - "2019/capetown/"
ccgilroy:
  - "_data/2019/seattle/"
  - "2019/seattle/"
  - "2019/live-stream.md"
MariaYR:
  - "_data/2019/"
  - "2019/"
  - "2019/live-stream.md"
ausmani23:
  - "_data/2019/nyu-nyc/"
  - "2019/nyu-nyc/"
  - "2019/live-stream.md"
  - "_data/2019/"
  - "2019/"
  - "assests/"
fmerhout:
  - "_data/2019/"
  - "assets/images"
  - "2019/"
marcone84:
  - "_data/2019/"
  - "2019/"
  - "assets/images"
taylorwhitten:
  - "_data/2019/"
  - "2019/"
  - "assets/"
haohanchen:
  - "_data/2019/"
  - "2019/"
  - "assets/images"
cschwem2er:
  - "_data/2019/"
  - "2019/"
  - "assets/"
rchew:
  - "_data/2019/"
  - "2019/"
  - "assets/"
ellliottt:
  - "_data/2019/"
  - "2019/"
  - "assets/"
Lenchickk:
  - "_data/2019/"
  - "2019/"
  - "assets/"
sxzh:
  - "_data/"
  - "2019/"
  - "assets/"
oscarmendezm-uanl:
  - "_data/2019/"
  - "2019/"
  - "assets/"
atkindel:
  - "_data/2019/"
  - "2019/"
  - "assets/"
ngallagher1218:
  - "_data/2019/"
  - "2019/"
  - "assets/"
